service: ymca-scraper
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  bookFreeWeights:
    handler: handler.bookFreeWeights
    events:
      - schedule:
          rate: cron(0 4 * * ? *)
          enabled: true
          input:
            monday: "1:30 pm"
            thursday: "1:30 pm"
            saturday: "1:30 pm"
